INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_ZIGBEE_OQPSK zigbee_OQPSK)

FIND_PATH(
    ZIGBEE_OQPSK_INCLUDE_DIRS
    NAMES zigbee_OQPSK/api.h
    HINTS $ENV{ZIGBEE_OQPSK_DIR}/include
        ${PC_ZIGBEE_OQPSK_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    ZIGBEE_OQPSK_LIBRARIES
    NAMES gnuradio-zigbee_OQPSK
    HINTS $ENV{ZIGBEE_OQPSK_DIR}/lib
        ${PC_ZIGBEE_OQPSK_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(ZIGBEE_OQPSK DEFAULT_MSG ZIGBEE_OQPSK_LIBRARIES ZIGBEE_OQPSK_INCLUDE_DIRS)
MARK_AS_ADVANCED(ZIGBEE_OQPSK_LIBRARIES ZIGBEE_OQPSK_INCLUDE_DIRS)

